version: 2.1

orbs:
  circle-compare-url: iynere/compare-url@0.4.5
  orb-tools: circleci/orb-tools@2.0.2
  slack: circleci/slack@dev:alpha

executors:
  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli

  ci-base:
    resource_class: small
    docker:
      - image: cibuilds/base

  lint:
    resource_class: small
    docker:
      - image: singapore/lint-condo

jobs:
  lint:
    executor: lint
    steps:
      - checkout
      - run: yamllint .

  # validate goes here: see workflow

  publish-dev:
    executor: cli
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run:
          name: publish dev versions
          command: |
            # for integration testing
            circleci orb publish workspace/orb.yml circleci/slack@dev:alpha --token $CIRCLE_TOKEN

            # for transparency
            circleci orb publish workspace/orb.yml circleci/slack@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

            # for potentially promoting to prod
            circleci orb publish workspace/orb.yml circleci/slack@dev:${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

      - store_artifacts:
          path: workspace/orb.yml

  trigger-integration:
    executor: ci-base
    parameters:
      tag:
        type: enum
        default: "integration"
        enum: ["integration", master]
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "79:ae:f5:10:17:8a:d2:9a:ed:63:5c:b0:92:66:23:49"

      - run:
          name: git config
          command: |
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
            git config --global user.name "$CIRCLE_USERNAME"

      - circle-compare-url/reconstruct

      - run:
          name: trigger integration workflow, possible patch / minor / major release
          command: |
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)

            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            echo "Commit range: $COMMIT_RANGE"

            if [[ $(git diff $COMMIT_RANGE --name-status | grep -e "src/commands" -e "src/jobs") ]]; then
              INTEGRATION_TAG=<<parameters.tag>>-major-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            elif [[ $(git diff $COMMIT_RANGE --name-status | grep -e "src/executors" -e "src/examples" -e "src/@orb.yml") ]]; then
              INTEGRATION_TAG=<<parameters.tag>>-minor-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            else
              INTEGRATION_TAG=<<parameters.tag>>-patch-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            fi

            git tag $INTEGRATION_TAG
            git push origin $INTEGRATION_TAG

  notifytest:
    executor: ci-base
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - slack/notify:
          message: "notification test for the Slack orb, triggered by *<https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commit/${CIRCLE_SHA1}|commit ${CIRCLE_SHA1}>* on ${CIRCLE_PROJECT_REPONAME}'s *${CIRCLE_BRANCH}* branch (<https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|workflow here>)"
          color: "#f4aa42"
          mentions: "${ORBS_USER_GROUP_UUID}"

  statustestpass:
    executor: ci-base
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - slack/status:
          mentions: "${ORBS_USER_GROUP_UUID}"

  # statustestfail:
  #   executor: ci-base
  #   steps:
  #     - run: exit 1 #toggle this to force success or status for testing
  #     - slack/status:
  #         mentions: "${ORBS_USER_GROUP_UUID}"

  approvaltest:
    executor: ci-base
    steps:
      - slack/approval:
          mentions: "${ORBS_USER_GROUP_UUID}"

  dev-promote-prod:
    executor: cli
    parameters:
      release:
        type: enum
        default: "patch"
        enum: ["patch", "minor", "major"]
    steps:
      - run:
          name: major release if changes to src/commands or src/jobs; minor if to src/examples, src/executors, or src/@orb.yml; otherwise patch
          command: circleci orb publish promote circleci/slack@dev:${CIRCLE_SHA1:0:7} <<parameters.release>> --token $CIRCLE_TOKEN

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [notifytest-master, statustestpass-master, approvaltest-master, approval-notification-job-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - lint

      - orb-tools/pack:
          name: pack-validate
          source-dir: src
          destination-orb-path: orb.yml
          workspace-path: orb.yml
          artifact-path: orb.yml
          requires:
            - lint

      - publish-dev:
          context: orb-publishing
          requires:
            - pack-validate

      - trigger-integration:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - publish-dev
          filters:
            branches:
              ignore: master

      - trigger-integration:
          name: trigger-integration-master
          context: orb-publishing
          tag: master
          requires:
            - publish-dev
          filters:
            branches:
              only: master

  integration_tests-prod_deploy:
    jobs:
      # triggered by non-master branch commits
      - notifytest:
          name: notifytest-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - statustestpass:
          name: statustestpass-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - approvaltest:
          name: approvaltest-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - slack/approval-notification:
          name: approval-notification-job-dev
          context: orb-publishing
          mentions: "${ORBS_USER_GROUP_UUID}"
          filters: *integration-dev_filters

      # triggered by master branch commits
      - notifytest:
          name: notifytest-master
          context: orb-publishing
          filters: *integration-master_filters

      - statustestpass:
          name: statustestpass-master
          context: orb-publishing
          filters: *integration-master_filters

      - approvaltest:
          name: approvaltest-master
          context: orb-publishing
          filters: *integration-master_filters

      - slack/approval-notification:
          name: approval-notification-job-master
          context: orb-publishing
          mentions: "${ORBS_USER_GROUP_UUID}"
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - dev-promote-prod:
          name: dev-promote-minor
          release: minor
          context: orb-publishing
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - dev-promote-prod:
          name: dev-promote-major
          release: major
          context: orb-publishing
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
